
import com.itextpdf.text.DocumentException;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author albertosml
 */
public class CalcularSueldo extends javax.swing.JFrame {

    private String nombre_directorio;
    
    /**
     * Creates new form Inicio
     */
    public CalcularSueldo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Calcular Sueldo  -  ControlaSueldos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mes = new com.toedter.calendar.JMonthChooser();
        anio = new com.toedter.calendar.JYearChooser();
        tit_mes = new javax.swing.JLabel();
        tit_anio = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        ruta = new javax.swing.JTextField();
        btn_directorio = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        elem1 = new javax.swing.JMenu();
        elem1item1 = new javax.swing.JMenuItem();
        elem1item2 = new javax.swing.JMenuItem();
        elem2 = new javax.swing.JMenu();
        elem2item1 = new javax.swing.JMenuItem();
        elem3 = new javax.swing.JMenu();
        elem3item1 = new javax.swing.JMenuItem();
        elem3item2 = new javax.swing.JMenuItem();
        elem3item3 = new javax.swing.JMenuItem();
        elem3item4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tit_mes.setText("Mes:");

        tit_anio.setText("Año:");

        btn_calcular.setText("Calcular Sueldo");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        ruta.setEditable(false);

        btn_directorio.setText("Elegir Directorio");
        btn_directorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_directorioActionPerformed(evt);
            }
        });

        elem1.setText("Inicio");
        elem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1ActionPerformed(evt);
            }
        });

        elem1item1.setText("Ir a Inicio");
        elem1item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item1ActionPerformed(evt);
            }
        });
        elem1.add(elem1item1);

        elem1item2.setText("Salir");
        elem1item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item2ActionPerformed(evt);
            }
        });
        elem1.add(elem1item2);

        menubar.add(elem1);

        elem2.setText("Trabajador");

        elem2item1.setText("Añadir Trabajador");
        elem2item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem2item1ActionPerformed(evt);
            }
        });
        elem2.add(elem2item1);

        menubar.add(elem2);

        elem3.setText("Otras Opciones");

        elem3item1.setText("Calcular Sueldo");
        elem3item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item1ActionPerformed(evt);
            }
        });
        elem3.add(elem3item1);

        elem3item2.setText("Resumen Salario");
        elem3item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item2ActionPerformed(evt);
            }
        });
        elem3.add(elem3item2);

        elem3item3.setText("Registrar Trabajado");
        elem3item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item3ActionPerformed(evt);
            }
        });
        elem3.add(elem3item3);

        elem3item4.setText("Ver Días Trabajados");
        elem3item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item4ActionPerformed(evt);
            }
        });
        elem3.add(elem3item4);

        menubar.add(elem3);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tit_anio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tit_mes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btn_directorio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tit_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tit_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_directorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btn_calcular)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elem2item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem2item1ActionPerformed
        if(!"AnadirTrabajador".equals(this.getClass().getSimpleName())) {
            AnadirTrabajador at = new AnadirTrabajador();
            at.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem2item1ActionPerformed

    private void elem3item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item2ActionPerformed
        if(!"ResumenSalario".equals(this.getClass().getSimpleName())) {
            ResumenSalario rs = new ResumenSalario();
            rs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item2ActionPerformed

    private void elem3item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item3ActionPerformed
        if(!"RegistrarTrabajado".equals(this.getClass().getSimpleName())) {
            RegistrarTrabajado rt = null;
            try {
                rt = new RegistrarTrabajado();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CalcularSueldo.class.getName()).log(Level.SEVERE, null, ex);
            }
            rt.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item3ActionPerformed

    private void elem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1ActionPerformed
    }//GEN-LAST:event_elem1ActionPerformed

    private void elem3item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item1ActionPerformed
        if(!"CalcularSueldo".equals(this.getClass().getSimpleName())) {
            CalcularSueldo cs = new CalcularSueldo();
            cs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item1ActionPerformed

    private void elem1item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_elem1item2ActionPerformed

    private void elem1item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item1ActionPerformed
        if(!"Inicio".equals(this.getClass().getSimpleName())) {
            Inicio i = null;
            try {
                i = new Inicio();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CalcularSueldo.class.getName()).log(Level.SEVERE, null, ex);
            }
            i.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem1item1ActionPerformed

    private void btn_directorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_directorioActionPerformed
        JFileChooser elector = new JFileChooser();
        elector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int r = elector.showOpenDialog(null);
        File f = elector.getSelectedFile();
        if(r == JFileChooser.APPROVE_OPTION) { // Si le da a aceptar
            nombre_directorio = f.getAbsolutePath();
            ruta.setText(nombre_directorio);
        }
    }//GEN-LAST:event_btn_directorioActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        if(!ruta.getText().isEmpty()){
            OperacionesPDF o = new OperacionesPDF();

            String s = new String();
            try {
                s = o.generatePDFSueldo(mes.getMonth(), anio.getYear(),ruta.getText());
                switch (s) {
                    case "error":
                        JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
                        break;
                    case "vacioerror":
                        JOptionPane.showMessageDialog(rootPane,"No hay trabajadores para calcular el sueldo");
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane,"Calculado el sueldo de los trabajadores con éxito");
                        break;
                }
                ruta.setText("");
            } catch (FileNotFoundException | DocumentException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CalcularSueldo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(rootPane,"Falta especificar el directorio donde se quiere almacenar el PDF con los sueldos de los trabajadores");
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void elem3item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item4ActionPerformed
        if(!"VerDiasTrabajados".equals(this.getClass().getSimpleName())) {
            VerDiasTrabajados vd = null;
            try {
                vd = new VerDiasTrabajados();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AnadirTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            vd.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CalcularSueldo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anio;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_directorio;
    private javax.swing.JMenu elem1;
    private javax.swing.JMenuItem elem1item1;
    private javax.swing.JMenuItem elem1item2;
    private javax.swing.JMenu elem2;
    private javax.swing.JMenuItem elem2item1;
    private javax.swing.JMenu elem3;
    private javax.swing.JMenuItem elem3item1;
    private javax.swing.JMenuItem elem3item2;
    private javax.swing.JMenuItem elem3item3;
    private javax.swing.JMenuItem elem3item4;
    private javax.swing.JMenuBar menubar;
    private com.toedter.calendar.JMonthChooser mes;
    private javax.swing.JTextField ruta;
    private javax.swing.JLabel tit_anio;
    private javax.swing.JLabel tit_mes;
    // End of variables declaration//GEN-END:variables
}
