import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerNumberModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author albertosml
 */
public class Inicio extends javax.swing.JFrame {

    private final HashMap<String, String> estados;
    
    /**
     * Creates new form Inicio
     */
    public Inicio() throws ClassNotFoundException {
        this.estados = new HashMap<String, String>();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio  -  ControlaSueldos");
        
        OperacionesBD o = new OperacionesBD();
        
        ArrayList<String> a = o.obtainSpinnerListInicio();
        if(a.get(0) != "error") {
            for(int i=0;i<a.size();i++) {
                String [] vector = a.get(i).split("_");
                a.set(i, vector[0]);
                estados.put(vector[0],vector[1]);
            }
            SpinnerListModel listModel = new SpinnerListModel(a);
        
            trabajadores.setModel(listModel);
            trabajadores.setValue(a.get(0));
            
            trabajado.setEnabled(Boolean.parseBoolean(estados.get(a.get(0))));
        }
        else {
            SpinnerListModel listModel = new SpinnerListModel(new String[]{""});
            trabajadores.setModel(listModel);
        }
        
        ((JSpinner.DefaultEditor) trabajadores.getEditor()).getTextField().setEditable(false);
        
        boolean active = Boolean.parseBoolean(estados.get(trabajadores.getValue())); 
        
        trabajado.setEnabled(active);
        if(active) {
            String t = (String) trabajadores.getValue();
            String [] v = t.split(":");

            try {
                trabajado.setSelected(o.searchMovimiento(v[0]));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        SpinnerNumberModel numeros = new SpinnerNumberModel(1,1,24,0.5);
        horas_trabajadas.setModel(numeros);
        
        ((JSpinner.DefaultEditor) horas_trabajadas.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trabajadores = new javax.swing.JSpinner();
        titulo = new javax.swing.JLabel();
        trabajado = new javax.swing.JToggleButton();
        tit_horast = new javax.swing.JLabel();
        horas_trabajadas = new javax.swing.JSpinner();
        menubar = new javax.swing.JMenuBar();
        elem1 = new javax.swing.JMenu();
        elem1item1 = new javax.swing.JMenuItem();
        elem1item2 = new javax.swing.JMenuItem();
        elem2 = new javax.swing.JMenu();
        elem2item1 = new javax.swing.JMenuItem();
        elem2item2 = new javax.swing.JMenuItem();
        elem3 = new javax.swing.JMenu();
        elem3item1 = new javax.swing.JMenuItem();
        elem3item2 = new javax.swing.JMenuItem();
        elem3item3 = new javax.swing.JMenuItem();
        elem3item4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        trabajadores.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trabajadoresStateChanged(evt);
            }
        });

        titulo.setText("Trabajador:");

        trabajado.setText("Trabajado");
        trabajado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadoActionPerformed(evt);
            }
        });

        tit_horast.setText("Horas Trabajadas:");

        elem1.setText("Inicio");
        elem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1ActionPerformed(evt);
            }
        });

        elem1item1.setText("Ir a Inicio");
        elem1item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item1ActionPerformed(evt);
            }
        });
        elem1.add(elem1item1);

        elem1item2.setText("Salir");
        elem1item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item2ActionPerformed(evt);
            }
        });
        elem1.add(elem1item2);

        menubar.add(elem1);

        elem2.setText("Trabajador");

        elem2item1.setText("Añadir Trabajador");
        elem2item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem2item1ActionPerformed(evt);
            }
        });
        elem2.add(elem2item1);

        elem2item2.setText("Modificar Trabajador");
        elem2item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem2item2ActionPerformed(evt);
            }
        });
        elem2.add(elem2item2);

        menubar.add(elem2);

        elem3.setText("Otras Opciones");

        elem3item1.setText("Calcular Sueldo");
        elem3item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item1ActionPerformed(evt);
            }
        });
        elem3.add(elem3item1);

        elem3item2.setText("Resumen Salario");
        elem3item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item2ActionPerformed(evt);
            }
        });
        elem3.add(elem3item2);

        elem3item3.setText("Registrar Trabajado");
        elem3item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item3ActionPerformed(evt);
            }
        });
        elem3.add(elem3item3);

        elem3item4.setText("Ver Días Trabajados");
        elem3item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item4ActionPerformed(evt);
            }
        });
        elem3.add(elem3item4);

        menubar.add(elem3);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo)
                        .addGap(18, 18, 18)
                        .addComponent(trabajadores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(trabajado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tit_horast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horas_trabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(trabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_horast)
                    .addComponent(horas_trabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(trabajado)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elem2item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem2item1ActionPerformed
        if(!"AnadirTrabajador".equals(this.getClass().getSimpleName())) {
            AnadirTrabajador at = new AnadirTrabajador();
            at.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem2item1ActionPerformed

    private void elem3item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item2ActionPerformed
        if(!"ResumenSalario".equals(this.getClass().getSimpleName())) {
            ResumenSalario rs = new ResumenSalario();
            rs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item2ActionPerformed

    private void elem3item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item3ActionPerformed
        if(!"RegistrarTrabajado".equals(this.getClass().getSimpleName())) {
            RegistrarTrabajado rt = null;
            try {
                rt = new RegistrarTrabajado();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            rt.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item3ActionPerformed

    private void elem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1ActionPerformed
    }//GEN-LAST:event_elem1ActionPerformed

    private void elem2item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem2item2ActionPerformed
        String s = (String) trabajadores.getValue();
        if(!s.isEmpty()) {
            String [] v = s.split(":");
            ModificarTrabajador mt = null;
            try {
                mt = new ModificarTrabajador(v[0]);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            mt.setVisible(true);
            this.dispose();
        }
        else JOptionPane.showMessageDialog(rootPane,"No se ha seleccionado al trabajador");
    }//GEN-LAST:event_elem2item2ActionPerformed

    private void elem3item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item1ActionPerformed
        if(!"CalcularSueldo".equals(this.getClass().getSimpleName())) {
            CalcularSueldo cs = new CalcularSueldo();
            cs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item1ActionPerformed

    private void elem1item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_elem1item2ActionPerformed

    private void elem1item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item1ActionPerformed
        if(!"Inicio".equals(this.getClass().getSimpleName())) {
            Inicio i = null;
            try {
                i = new Inicio();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            i.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem1item1ActionPerformed

    private void trabajadoresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trabajadoresStateChanged
        // Ir a la base de datos y comprobar si se ha registrado un movimiento
        // con la fecha actual y el nombre del trabajador 
        
        boolean activo = Boolean.parseBoolean(estados.get(trabajadores.getValue())); 
        
        trabajado.setEnabled(activo);
        if(activo) {
            String t = (String) trabajadores.getValue();
            String [] v = t.split(":");

            OperacionesBD o = new OperacionesBD();
            try {
                trabajado.setSelected(o.searchMovimiento(v[0]));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_trabajadoresStateChanged

    private void trabajadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadoActionPerformed
        //Obtener id (v[0])
        String t = (String) trabajadores.getValue();
        String [] v = t.split(":");
        
        OperacionesBD o = new OperacionesBD();
        if(!trabajado.isSelected()) { // Se elimina el movimiento si estaba seleccionado
            String s = new String();
            try {
                s = o.deleteMovimiento(v[0]);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(s.contains("error")) JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
            else JOptionPane.showMessageDialog(rootPane,"Registro de trabajo eliminado con éxito");
        }
        else { // Se inserta el movimiento si no estaba seleccionado
            String s = new String();
            try {
                s = o.insertMovimiento(v[0],Float.parseFloat(horas_trabajadas.getValue().toString().replace(",", ".")));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(s.contains("error")) JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
            else JOptionPane.showMessageDialog(rootPane,"Registro de trabajo insertado con éxito");  
        }
    }//GEN-LAST:event_trabajadoActionPerformed

    private void elem3item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item4ActionPerformed
        if(!"VerDiasTrabajados".equals(this.getClass().getSimpleName())) {
            VerDiasTrabajados vd = null;
            try {
                vd = new VerDiasTrabajados();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AnadirTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            vd.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu elem1;
    private javax.swing.JMenuItem elem1item1;
    private javax.swing.JMenuItem elem1item2;
    private javax.swing.JMenu elem2;
    private javax.swing.JMenuItem elem2item1;
    private javax.swing.JMenuItem elem2item2;
    private javax.swing.JMenu elem3;
    private javax.swing.JMenuItem elem3item1;
    private javax.swing.JMenuItem elem3item2;
    private javax.swing.JMenuItem elem3item3;
    private javax.swing.JMenuItem elem3item4;
    private javax.swing.JSpinner horas_trabajadas;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JLabel tit_horast;
    private javax.swing.JLabel titulo;
    private javax.swing.JToggleButton trabajado;
    private javax.swing.JSpinner trabajadores;
    // End of variables declaration//GEN-END:variables
}
