
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author albertosml
 */
public class ModificarTrabajador extends javax.swing.JFrame {

    private String nombre_archivo;
    private String id;
    
    /**
     * Creates new form Inicio
     */
    public ModificarTrabajador(String id) throws ClassNotFoundException, IOException {
        this.id = id;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Modificar Trabajador  -  ControlaSueldos");
        
        OperacionesBD o = new OperacionesBD();
        ArrayList<Object> a = o.obtainTrabajador(id);
        if(a.get(0) != "error") {
            nombre.setText((String) a.get(0));
            nif.setText((String) a.get(1));
            nafiliacion.setText((String) a.get(2));
            if(a.get(3) != null) {
                byte [] b = (byte[]) a.get(3);
                InputStream in = new ByteArrayInputStream(b);
                BufferedImage image = ImageIO.read(in);
                ImageIcon fot = new ImageIcon(image);
                Icon icono = new ImageIcon(fot.getImage().getScaledInstance(imagen.getWidth(),imagen.getHeight(),Image.SCALE_DEFAULT));
                imagen.setIcon(icono);
            }
            precioHora.setText(a.get(4).toString());
            btn_activo.setSelected((boolean) a.get(5));
        }
        else {
            JOptionPane.showMessageDialog(rootPane,"No se ha encontrado a ningún trabajador con ese id.");
            this.btn_activo.setEnabled(false);
            this.btn_elegirimagen.setEnabled(false);
            this.btn_modNIF.setEnabled(false);
            this.btn_modimagen.setEnabled(false);
            this.btn_modnafiliacion.setEnabled(false);
            this.btn_modnombre.setEnabled(false);
            this.btn_modpreciohora.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tit_nombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        tit_nif = new javax.swing.JLabel();
        nif = new javax.swing.JTextField();
        tit_nafiliacion = new javax.swing.JLabel();
        nafiliacion = new javax.swing.JTextField();
        tit_firma = new javax.swing.JLabel();
        precioHora = new javax.swing.JTextField();
        firma = new javax.swing.JTextField();
        btn_elegirimagen = new javax.swing.JButton();
        tit_precioHora = new javax.swing.JLabel();
        btn_modpreciohora = new javax.swing.JButton();
        tit_estado = new javax.swing.JLabel();
        btn_activo = new javax.swing.JToggleButton();
        btn_modnombre = new javax.swing.JButton();
        btn_modNIF = new javax.swing.JButton();
        btn_modnafiliacion = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        btn_modimagen = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        elem1 = new javax.swing.JMenu();
        elem1item1 = new javax.swing.JMenuItem();
        elem1item2 = new javax.swing.JMenuItem();
        elem2 = new javax.swing.JMenu();
        elem2item1 = new javax.swing.JMenuItem();
        elem3 = new javax.swing.JMenu();
        elem3item1 = new javax.swing.JMenuItem();
        elem3item2 = new javax.swing.JMenuItem();
        elem3item3 = new javax.swing.JMenuItem();
        elem3item4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tit_nombre.setText("Nombre:");

        tit_nif.setText("NIF:");

        tit_nafiliacion.setText("Número Afiliación:");

        tit_firma.setText("Firma:");

        btn_elegirimagen.setText("Elegir Imagen");
        btn_elegirimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elegirimagenActionPerformed(evt);
            }
        });

        tit_precioHora.setText("Precio/Hora:");

        btn_modpreciohora.setText("Cambiar Precio/Hora");
        btn_modpreciohora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modpreciohoraActionPerformed(evt);
            }
        });

        tit_estado.setText("Estado:");

        btn_activo.setText("Activo");
        btn_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_activoActionPerformed(evt);
            }
        });

        btn_modnombre.setText("Cambiar Nombre");
        btn_modnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modnombreActionPerformed(evt);
            }
        });

        btn_modNIF.setText("Cambiar NIF");
        btn_modNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modNIFActionPerformed(evt);
            }
        });

        btn_modnafiliacion.setText("Cambiar Nº Afiliación");
        btn_modnafiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modnafiliacionActionPerformed(evt);
            }
        });

        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_modimagen.setText("Cambiar Firma");
        btn_modimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modimagenActionPerformed(evt);
            }
        });

        elem1.setText("Inicio");
        elem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1ActionPerformed(evt);
            }
        });

        elem1item1.setText("Ir a Inicio");
        elem1item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item1ActionPerformed(evt);
            }
        });
        elem1.add(elem1item1);

        elem1item2.setText("Salir");
        elem1item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item2ActionPerformed(evt);
            }
        });
        elem1.add(elem1item2);

        menubar.add(elem1);

        elem2.setText("Trabajador");

        elem2item1.setText("Añadir Trabajador");
        elem2item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem2item1ActionPerformed(evt);
            }
        });
        elem2.add(elem2item1);

        menubar.add(elem2);

        elem3.setText("Otras Opciones");

        elem3item1.setText("Calcular Sueldo");
        elem3item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item1ActionPerformed(evt);
            }
        });
        elem3.add(elem3item1);

        elem3item2.setText("Resumen Salario");
        elem3item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item2ActionPerformed(evt);
            }
        });
        elem3.add(elem3item2);

        elem3item3.setText("Registrar Trabajado");
        elem3item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item3ActionPerformed(evt);
            }
        });
        elem3.add(elem3item3);

        elem3item4.setText("Ver Días Trabajados");
        elem3item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item4ActionPerformed(evt);
            }
        });
        elem3.add(elem3item4);

        menubar.add(elem3);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tit_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_modnombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tit_nif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nif, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_modNIF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tit_nafiliacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nafiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tit_precioHora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_modpreciohora, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_modnafiliacion))))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tit_firma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firma, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_modimagen)
                            .addComponent(btn_elegirimagen))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tit_estado)
                        .addGap(28, 28, 28)
                        .addComponent(btn_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_nombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modNIF))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_nafiliacion)
                    .addComponent(nafiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modnafiliacion))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tit_firma)
                    .addComponent(btn_elegirimagen))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_modimagen)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_precioHora)
                    .addComponent(precioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modpreciohora))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tit_estado)
                    .addComponent(btn_activo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elem2item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem2item1ActionPerformed
        if(!"AnadirTrabajador".equals(this.getClass().getSimpleName())) {
            AnadirTrabajador at = new AnadirTrabajador();
            at.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem2item1ActionPerformed

    private void elem3item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item2ActionPerformed
        if(!"ResumenSalario".equals(this.getClass().getSimpleName())) {
            ResumenSalario rs = new ResumenSalario();
            rs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item2ActionPerformed

    private void elem3item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item3ActionPerformed
        if(!"RegistrarTrabajado".equals(this.getClass().getSimpleName())) {
            RegistrarTrabajado rt = null;
            try {
                rt = new RegistrarTrabajado();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            rt.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item3ActionPerformed

    private void elem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1ActionPerformed
    }//GEN-LAST:event_elem1ActionPerformed

    private void elem3item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item1ActionPerformed
        if(!"CalcularSueldo".equals(this.getClass().getSimpleName())) {
            CalcularSueldo cs = new CalcularSueldo();
            cs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item1ActionPerformed

    private void elem1item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_elem1item2ActionPerformed

    private void elem1item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item1ActionPerformed
        if(!"Inicio".equals(this.getClass().getSimpleName())) {
            Inicio i = null;
            try {
                i = new Inicio();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            i.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem1item1ActionPerformed

    private void btn_elegirimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elegirimagenActionPerformed
        JFileChooser elector = new JFileChooser();
        elector.setFileFilter(new FileNameExtensionFilter("Imágenes","jpeg","jpg","gif","bmp","png"));
        int r = elector.showOpenDialog(null);
        File f = elector.getSelectedFile();
        if(r == JFileChooser.APPROVE_OPTION) { // Si le da a aceptar
            nombre_archivo = f.getAbsolutePath();
            firma.setText(nombre_archivo);
        }
    }//GEN-LAST:event_btn_elegirimagenActionPerformed

    private void btn_modnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modnombreActionPerformed
        String name = nombre.getText();
        if(!name.isEmpty() && name.length() <= 60 ) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.updateTrabajador(id, name, 1);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio de nombre del trabajador se ha realizado con éxito");
        }
        else JOptionPane.showMessageDialog(rootPane,"No se ha introducido el nuevo nombre del trabajador o este es demasiado largo");
    }//GEN-LAST:event_btn_modnombreActionPerformed

    private void btn_modNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modNIFActionPerformed
        String NIF = nif.getText();
        if(NIF.matches("[0-9A-Z]+") && NIF.length() == 9) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.updateTrabajador(id, NIF, 2);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio de NIF del trabajador se ha realizado con éxito");
        }
        else JOptionPane.showMessageDialog(rootPane,"No se ha introducido el NIF del trabajador, debe tener 9 caracteres");
    }//GEN-LAST:event_btn_modNIFActionPerformed

    private void btn_modnafiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modnafiliacionActionPerformed
        String num_afiliacion = nafiliacion.getText();
        if(num_afiliacion.matches("[0-9]+") && num_afiliacion.length() == 12) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.updateTrabajador(id, num_afiliacion , 3);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio del número de afiliación del trabajador se ha realizado con éxito");
        }
        else JOptionPane.showMessageDialog(rootPane,"No se ha introducido el número de afiliación del trabajador, debe tener 12 caracteres");
    }//GEN-LAST:event_btn_modnafiliacionActionPerformed

    private void btn_modimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modimagenActionPerformed
        String ruta_firma = firma.getText();
        if(!ruta_firma.isEmpty()) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.updateTrabajador(id, ruta_firma , 4);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio de la firma del trabajador se ha realizado con éxito");
            ImageIcon fot = new ImageIcon(ruta_firma);
            Icon icono = new ImageIcon(fot.getImage().getScaledInstance(imagen.getWidth(),imagen.getHeight(),Image.SCALE_DEFAULT));
            imagen.setIcon(icono);
            firma.setText("");
        }
        else JOptionPane.showMessageDialog(rootPane,"No se ha introducido la imagen de la firma del trabajador");
    }//GEN-LAST:event_btn_modimagenActionPerformed

    private void btn_modpreciohoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modpreciohoraActionPerformed
        String pHora = precioHora.getText();
        if(pHora.matches("[0-9]+[.][0-9]+") || pHora.matches("[0-9]+")) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.updateTrabajador(id, pHora , 5);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio del precio por hora del trabajador se ha realizado con éxito");
        }
        else JOptionPane.showMessageDialog(rootPane,"No se ha introducido el nuevo precio por hora del trabajador");
    }//GEN-LAST:event_btn_modpreciohoraActionPerformed

    private void btn_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_activoActionPerformed
        OperacionesBD o = new OperacionesBD();
        try {
            boolean activo = btn_activo.isSelected();
            if(activo) o.updateTrabajador(id, "1" , 6);  
            else o.updateTrabajador(id, "0" , 6);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane,"El cambio de estado del trabajador se ha realizado con éxito");
    }//GEN-LAST:event_btn_activoActionPerformed

    private void elem3item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item4ActionPerformed
        if(!"VerDiasTrabajados".equals(this.getClass().getSimpleName())) {
            VerDiasTrabajados vd = null;
            try {
                vd = new VerDiasTrabajados();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AnadirTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            vd.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_activo;
    private javax.swing.JButton btn_elegirimagen;
    private javax.swing.JButton btn_modNIF;
    private javax.swing.JButton btn_modimagen;
    private javax.swing.JButton btn_modnafiliacion;
    private javax.swing.JButton btn_modnombre;
    private javax.swing.JButton btn_modpreciohora;
    private javax.swing.JMenu elem1;
    private javax.swing.JMenuItem elem1item1;
    private javax.swing.JMenuItem elem1item2;
    private javax.swing.JMenu elem2;
    private javax.swing.JMenuItem elem2item1;
    private javax.swing.JMenu elem3;
    private javax.swing.JMenuItem elem3item1;
    private javax.swing.JMenuItem elem3item2;
    private javax.swing.JMenuItem elem3item3;
    private javax.swing.JMenuItem elem3item4;
    private javax.swing.JTextField firma;
    private javax.swing.JLabel imagen;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JTextField nafiliacion;
    private javax.swing.JTextField nif;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precioHora;
    private javax.swing.JLabel tit_estado;
    private javax.swing.JLabel tit_firma;
    private javax.swing.JLabel tit_nafiliacion;
    private javax.swing.JLabel tit_nif;
    private javax.swing.JLabel tit_nombre;
    private javax.swing.JLabel tit_precioHora;
    // End of variables declaration//GEN-END:variables
}
