
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author albertosml
 */
public class ResumenSalario extends javax.swing.JFrame {

    private Calendar cal = Calendar.getInstance();
    /**
     * Creates new form Inicio
     */
    public ResumenSalario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Resumen Salario  -  ControlaSueldos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_campania = new javax.swing.JLabel();
        anio_inicio = new com.toedter.calendar.JYearChooser();
        anio_final = new com.toedter.calendar.JYearChooser();
        guion = new javax.swing.JLabel();
        btn_obtenerresumen = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        elem1 = new javax.swing.JMenu();
        elem1item1 = new javax.swing.JMenuItem();
        elem1item2 = new javax.swing.JMenuItem();
        elem2 = new javax.swing.JMenu();
        elem2item1 = new javax.swing.JMenuItem();
        elem3 = new javax.swing.JMenu();
        elem3item1 = new javax.swing.JMenuItem();
        elem3item2 = new javax.swing.JMenuItem();
        elem3item3 = new javax.swing.JMenuItem();
        elem3item4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_campania.setText("Campaña:");

        anio_inicio.setValue(cal.get(Calendar.YEAR)-1);

        guion.setText("_");

        btn_obtenerresumen.setText("Obtener Resumen");
        btn_obtenerresumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obtenerresumenActionPerformed(evt);
            }
        });

        elem1.setText("Inicio");
        elem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1ActionPerformed(evt);
            }
        });

        elem1item1.setText("Ir a Inicio");
        elem1item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item1ActionPerformed(evt);
            }
        });
        elem1.add(elem1item1);

        elem1item2.setText("Salir");
        elem1item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem1item2ActionPerformed(evt);
            }
        });
        elem1.add(elem1item2);

        menubar.add(elem1);

        elem2.setText("Trabajador");

        elem2item1.setText("Añadir Trabajador");
        elem2item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem2item1ActionPerformed(evt);
            }
        });
        elem2.add(elem2item1);

        menubar.add(elem2);

        elem3.setText("Otras Opciones");

        elem3item1.setText("Calcular Sueldo");
        elem3item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item1ActionPerformed(evt);
            }
        });
        elem3.add(elem3item1);

        elem3item2.setText("Resumen Salario");
        elem3item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item2ActionPerformed(evt);
            }
        });
        elem3.add(elem3item2);

        elem3item3.setText("Registrar Trabajado");
        elem3item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item3ActionPerformed(evt);
            }
        });
        elem3.add(elem3item3);

        elem3item4.setText("Ver Días Trabajados");
        elem3item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem3item4ActionPerformed(evt);
            }
        });
        elem3.add(elem3item4);

        menubar.add(elem3);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn_obtenerresumen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txt_campania))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(anio_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(guion)
                        .addGap(54, 54, 54)
                        .addComponent(anio_final, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt_campania)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anio_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anio_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guion))
                .addGap(53, 53, 53)
                .addComponent(btn_obtenerresumen)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elem2item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem2item1ActionPerformed
        if(!"AnadirTrabajador".equals(this.getClass().getSimpleName())) {
            AnadirTrabajador at = new AnadirTrabajador();
            at.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem2item1ActionPerformed

    private void elem3item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item2ActionPerformed
        if(!"ResumenSalario".equals(this.getClass().getSimpleName())) {
            ResumenSalario rs = new ResumenSalario();
            rs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item2ActionPerformed

    private void elem3item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item3ActionPerformed
        if(!"RegistrarTrabajado".equals(this.getClass().getSimpleName())) {
            RegistrarTrabajado rt = null;
            try {
                rt = new RegistrarTrabajado();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ResumenSalario.class.getName()).log(Level.SEVERE, null, ex);
            }
            rt.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item3ActionPerformed

    private void elem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1ActionPerformed
    }//GEN-LAST:event_elem1ActionPerformed

    private void elem3item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item1ActionPerformed
        if(!"CalcularSueldo".equals(this.getClass().getSimpleName())) {
            CalcularSueldo cs = new CalcularSueldo();
            cs.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item1ActionPerformed

    private void elem1item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_elem1item2ActionPerformed

    private void elem1item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem1item1ActionPerformed
        if(!"Inicio".equals(this.getClass().getSimpleName())) {
            Inicio i = null;
            try {
                i = new Inicio();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ResumenSalario.class.getName()).log(Level.SEVERE, null, ex);
            }
            i.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem1item1ActionPerformed

    private void btn_obtenerresumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obtenerresumenActionPerformed
        int inicio = anio_inicio.getYear();
        int fin = anio_final.getYear();
        if((fin - inicio) == 1) {
            TablaResultado t = null;
            try {
                t = new TablaResultado(inicio,fin);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ResumenSalario.class.getName()).log(Level.SEVERE, null, ex);
            }
            t.setVisible(true);
        }
        else JOptionPane.showMessageDialog(rootPane,"Hay más de un año de diferencia entre el año de inicio y de final de campaña");
    }//GEN-LAST:event_btn_obtenerresumenActionPerformed

    private void elem3item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem3item4ActionPerformed
        if(!"VerDiasTrabajados".equals(this.getClass().getSimpleName())) {
            VerDiasTrabajados vd = null;
            try {
                vd = new VerDiasTrabajados();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AnadirTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            vd.setVisible(true);
            this.dispose();   
        }
    }//GEN-LAST:event_elem3item4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ResumenSalario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anio_final;
    private com.toedter.calendar.JYearChooser anio_inicio;
    private javax.swing.JButton btn_obtenerresumen;
    private javax.swing.JMenu elem1;
    private javax.swing.JMenuItem elem1item1;
    private javax.swing.JMenuItem elem1item2;
    private javax.swing.JMenu elem2;
    private javax.swing.JMenuItem elem2item1;
    private javax.swing.JMenu elem3;
    private javax.swing.JMenuItem elem3item1;
    private javax.swing.JMenuItem elem3item2;
    private javax.swing.JMenuItem elem3item3;
    private javax.swing.JMenuItem elem3item4;
    private javax.swing.JLabel guion;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JLabel txt_campania;
    // End of variables declaration//GEN-END:variables
}
